<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VijayMalu" name="WD_Training.TestNG_Test_BMethod" tests="2" failures="1" timestamp="15 Jul 2016 16:26:29 GMT" time="2.954" errors="0">
  <testcase name="Login" time="1.818" classname="WD_Training.TestNG_Test_BMethod">
    <failure type="java.lang.AssertionError" message="expected [Sign On: Mercury Tours] but found [Sign-on: Mercury Tours]">
      <![CDATA[java.lang.AssertionError: expected [Sign On: Mercury Tours] but found [Sign-on: Mercury Tours]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at WD_Training.TestNG_Test_BMethod.Login(TestNG_Test_BMethod.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase name="Register" time="1.136" classname="WD_Training.TestNG_Test_BMethod"/>
</testsuite> <!-- WD_Training.TestNG_Test_BMethod -->
